### ISSUE TITLE
https://github.com/openeyes/OpenEyes.git Cannot be found

### ISSUE THREAD

**Issue by vasilisrac13** [AppertaFoundation/openeyes#2]
https://github.com/openeyes/OpenEyes.git

Repository cannot be found.

Do you have any alternative?

**Comment by biskyt** [comment]
https://github.com/openeyes/OpenEyes.git is a private repo. This appertafoundation repo is the alternative public repo.

If there is a reference to the private repo in the installers/guides, please let us know so that we can correct.

Note there have been 2 big releases since your issue was opened, and therefore the issue may have been resolved. The latest release uses an entirely different default install mechanism (Docker)

**Comment by vasilisrac13** [comment]
Is there any installation guide with docker? I've never tried this way before. Thank you

**Comment by biskyt** [comment]
Hi. You can take a look at openeyes/docker. It has some basic instructions
